In [6]:
# 1. Import libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [7]:
#2. recurso de años de descaga
years = range(2000,2022)
id_table = [11, 10, 9, 8, 7, 3, 6, 13, 14, 15, 16, 25, 26, 27, 30, 33, 36, 40, 44, 46, 47, 48]
table_dict = {}

for i in range (0,len(years)):
    table_dict[years[i]] = id_table[i]

In [8]:
# 3. implementation of web scraping
for k in table_dict:
    
    # Create an URL object
    url = 'https://www.oica.net/category/production-statistics/'+str(k)+'-statistics/'
    
    # Create object page
    page = requests.get(url)
    
    # parser-lxml = Change html to Python friendly format
    # Obtain page's information
    soup = BeautifulSoup(page.text, 'lxml')
    
    # Obtain information from tag <table>
    table_tag = soup.find('table', id='tablepress-'+str(table_dict[k]))
    
    # Create Dataframe only for the first year

    if (k == 2000):
        
        # Obtain every title of columns with tag <th>
        headers = []
        for i in table_tag.find_all('th'):
            if (len(headers) <=4 ):
                title = i.text
                headers.append(title)
        headers.append("Year")

        # Create a dataframe
        cars_DF = pd.DataFrame(columns = headers)
        
        # Create a for loop to fill mydata for the first year
        for j in table_tag.find_all('tr')[1:]:
            row_data = j.find_all('td')
            row = [i.text for i in row_data]
            length = len(cars_DF)
            row.append(k)
            if (len(row) > 1):
                cars_DF.loc[length] = row
        
        print("The year: " + str(k) + " ok")
    
    else:
        for j in table_tag.find_all('tr')[1:]:
            row_data = j.find_all('td')
            row = [i.text for i in row_data]
            length = len(cars_DF)
            row.append(k)
            if (len(row) > 1):
                cars_DF.loc[length] = row
            
        print("The year: " + str(k) + " ok")
        
cars_DF

The year: 2000 ok
The year: 2001 ok
The year: 2002 ok
The year: 2003 ok
The year: 2004 ok
The year: 2005 ok
The year: 2006 ok
The year: 2007 ok
The year: 2008 ok
The year: 2009 ok
The year: 2010 ok
The year: 2011 ok
The year: 2012 ok
The year: 2013 ok
The year: 2014 ok
The year: 2015 ok
The year: 2016 ok
The year: 2017 ok
The year: 2018 ok
The year: 2019 ok
The year: 2020 ok
The year: 2021 ok

,Country/Region,Cars,Commercial Vehicles,Total,Total change,Year
0,Argentina,"238,921","100,711","339,632",11.4%,2000
1,Australia,"323,649","23,473","347,122",14.6%,2000
2,Austria,"115,979","25,047","141,026",1.2%,2000
3,Belgium,"912,233","121,061","1,033,294",1.6%,2000
4,Brazil,"1,351,998","329,519","1,681,517",24.5%,2000
...,...,...,...,...,...,...
875,UNITED KINGDOM,859575,72913,932488,-6%,2021
876,USA,1563060,7604154,9167214,4%,2021
877,UZBEKISTAN,236 667,4982,241649,-15%,2021
878,OTHERS,1645014,183930,1828944,,2021
879,TOTAL,57054295,23091693,80145988,3%,2021

In [12]:
# 4. Exportar dataset al csv
from pathlib import Path
filepath = Path('C:/Cars_sales.csv')
filepath.parent.mkdir(parents=True, exist_ok=True)
cars_DF.to_csv(filepath, index=False)

#cars_DF.to_csv(index=False)

In [5]:
pip install pipreqs

Collecting pipreqs
  Downloading pipreqs-0.4.11-py2.py3-none-any.whl (32 kB)
Collecting docopt
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting yarg
  Downloading yarg-0.1.9-py2.py3-none-any.whl (19 kB)
Requirement already satisfied: requests in c:\users\alexis\anaconda3\lib\site-packages (from yarg->pipreqs) (2.28.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\alexis\anaconda3\lib\site-packages (from requests->yarg->pipreqs) (1.26.11)
Requirement already satisfied: idna<4,>=2.5 in c:\users\alexis\anaconda3\lib\site-packages (from requests->yarg->pipreqs) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\alexis\anaconda3\lib\site-packages (from requests->yarg->pipreqs) (2022.9.14)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\alexis\anaconda3\lib\site-packages (from requests->yarg->pipreqs) (2.0.4)
Building wheels for collected packages: docopt
  Building wheel for docopt (setup.py): started
  Building wheel for docopt (setup.py): finished with status 'done'
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=a0a64f0c598dc241137da81edbc3ccb4704ff0fff8e97c79ccea384fcfdb6fe0
  Stored in directory: c:\users\alexis\appdata\local\pip\cache\wheels\70\4a\46\1309fc853b8d395e60bafaf1b6df7845bdd82c95fd59dd8d2b
Successfully built docopt
Installing collected packages: docopt, yarg, pipreqs
Successfully installed docopt-0.6.2 pipreqs-0.4.11 yarg-0.1.9
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.